<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Users Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 11px;
            color: #333;
            margin: 0;
            padding: 20px;
        }
        .header {
            text-align: center;
            border-bottom: 3px solid #3B82F6;
            padding-bottom: 20px;
            margin-bottom: 30px;
        }
        .header h1 {
            color: #3B82F6;
            margin: 0;
            font-size: 24px;
        }
        .header p {
            margin: 5px 0;
            color: #666;
        }
        .summary {
            display: flex;
            justify-content: space-around;
            margin-bottom: 20px;
            flex-wrap: wrap;
        }
        .summary-box {
            background-color: #f8f9fa;
            padding: 15px;
            border-radius: 5px;
            text-align: center;
            min-width: 150px;
            margin: 5px;
        }
        .summary-box h3 {
            margin: 0;
            color: #3B82F6;
            font-size: 14px;
        }
        .summary-box p {
            margin: 5px 0 0 0;
            font-size: 18px;
            font-weight: bold;
            color: #333;
        }
        .section {
            margin-bottom: 25px;
        }
        .section h2 {
            color: #3B82F6;
            font-size: 16px;
            border-bottom: 2px solid #3B82F6;
            padding-bottom: 5px;
            margin-bottom: 10px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
            font-size: 10px;
        }
        th {
            background-color: #3B82F6;
            color: white;
            padding: 8px;
            text-align: left;
            font-weight: bold;
        }
        td {
            padding: 6px;
            border-bottom: 1px solid #ddd;
        }
        tr:nth-child(even) {
            background-color: #f8f9fa;
        }
        .footer {
            margin-top: 30px;
            padding-top: 20px;
            border-top: 2px solid #ddd;
            text-align: center;
            color: #666;
            font-size: 10px;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Users Report</h1>
        <p>Date Range: {{ $startDate }} to {{ $endDate }}</p>
        <p>Generated on: {{ $exportDate }}</p>
        <p>Exported by: {{ $exportedBy }}</p>
    </div>

    <div class="summary">
        <div class="summary-box">
            <h3>Total Users</h3>
            <p>{{ $reports['total_users'] }}</p>
        </div>
        <div class="summary-box">
            <h3>Active Users</h3>
            <p>{{ $reports['active_users'] }}</p>
        </div>
        <div class="summary-box">
            <h3>New Users</h3>
            <p>{{ $reports['new_users'] }}</p>
        </div>
    </div>

    @if($reports['users_by_role']->count() > 0)
    <div class="section">
        <h2>Users by Role</h2>
        <table>
            <thead>
                <tr>
                    <th>Role</th>
                    <th>Count</th>
                </tr>
            </thead>
            <tbody>
                @foreach($reports['users_by_role'] as $role)
                <tr>
                    <td>{{ ucfirst($role->role) }}</td>
                    <td>{{ $role->count }}</td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
    @endif

    @if($reports['users_by_status']->count() > 0)
    <div class="section">
        <h2>Users by Status</h2>
        <table>
            <thead>
                <tr>
                    <th>Status</th>
                    <th>Count</th>
                </tr>
            </thead>
            <tbody>
                @foreach($reports['users_by_status'] as $status)
                <tr>
                    <td>{{ ucfirst($status->status) }}</td>
                    <td>{{ $status->count }}</td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
    @endif

    <div class="footer">
        <p>This is a confidential document. Generated by Dental Clinic Management System.</p>
        <p>Page generated at {{ now()->format('Y-m-d H:i:s') }}</p>
    </div>
</body>
</html>


