<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Financial Records Export</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 11px;
            color: #333;
            margin: 0;
            padding: 20px;
        }
        .header {
            text-align: center;
            border-bottom: 3px solid #3B82F6;
            padding-bottom: 20px;
            margin-bottom: 30px;
        }
        .header h1 {
            color: #3B82F6;
            margin: 0;
            font-size: 24px;
        }
        .header p {
            margin: 5px 0;
            color: #666;
        }
        .summary {
            display: flex;
            justify-content: space-around;
            margin-bottom: 20px;
            flex-wrap: wrap;
        }
        .summary-box {
            background-color: #f8f9fa;
            padding: 15px;
            border-radius: 5px;
            text-align: center;
            min-width: 150px;
            margin: 5px;
        }
        .summary-box h3 {
            margin: 0;
            color: #3B82F6;
            font-size: 14px;
        }
        .summary-box p {
            margin: 5px 0 0 0;
            font-size: 18px;
            font-weight: bold;
            color: #333;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
            font-size: 10px;
        }
        th {
            background-color: #3B82F6;
            color: white;
            padding: 8px;
            text-align: left;
            font-weight: bold;
        }
        td {
            padding: 6px;
            border-bottom: 1px solid #ddd;
        }
        tr:nth-child(even) {
            background-color: #f8f9fa;
        }
        .footer {
            margin-top: 30px;
            padding-top: 20px;
            border-top: 2px solid #ddd;
            text-align: center;
            color: #666;
            font-size: 10px;
        }
        .badge {
            display: inline-block;
            padding: 2px 6px;
            border-radius: 3px;
            font-size: 9px;
            font-weight: bold;
        }
        .badge-paid { background-color: #10B981; color: white; }
        .badge-pending { background-color: #F59E0B; color: white; }
        .badge-overdue { background-color: #EF4444; color: white; }
        .amount {
            font-weight: bold;
            color: #059669;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Financial Records Export Report</h1>
        <p>Date Range: {{ $startDate }} to {{ $endDate }}</p>
        <p>Generated on: {{ $exportDate }}</p>
        <p>Exported by: {{ $exportedBy }}</p>
    </div>

    <div class="summary">
        <div class="summary-box">
            <h3>Total Records</h3>
            <p>{{ $totalRecords }}</p>
        </div>
        <div class="summary-box">
            <h3>Total Amount</h3>
            <p class="amount">PHP {{ number_format($summary['total_amount'], 2) }}</p>
        </div>
        <div class="summary-box">
            <h3>Paid Amount</h3>
            <p class="amount">PHP {{ number_format($summary['paid_amount'], 2) }}</p>
        </div>
        <div class="summary-box">
            <h3>Pending Amount</h3>
            <p class="amount">PHP {{ number_format($summary['pending_amount'], 2) }}</p>
        </div>
    </div>

    <table>
        <thead>
            <tr>
                <th>Date</th>
                <th>Patient</th>
                <th>Description</th>
                <th>Amount</th>
                <th>Payment Method</th>
            </tr>
        </thead>
        <tbody>
            @forelse($records as $record)
            <tr>
                <td>{{ \Carbon\Carbon::parse($record->transaction_date)->format('M d, Y') }}</td>
                <td>{{ $record->patient->name ?? 'N/A' }}</td>
                <td>{{ $record->description ?? 'N/A' }}</td>
                <td class="amount">PHP {{ number_format($record->amount, 2) }}</td>
                <td>{{ ucfirst($record->payment_method ?? 'N/A') }}</td>
            </tr>
            @empty
            <tr>
                <td colspan="5" style="text-align: center; padding: 20px;">No financial records found</td>
            </tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">
        <p>This is a confidential document. Generated by Dental Clinic Management System.</p>
        <p>Page generated at {{ now()->format('Y-m-d H:i:s') }}</p>
    </div>
</body>
</html>


