<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Patients Export</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            color: #333;
            margin: 0;
            padding: 20px;
        }
        .header {
            text-align: center;
            border-bottom: 3px solid #3B82F6;
            padding-bottom: 20px;
            margin-bottom: 30px;
        }
        .header h1 {
            color: #3B82F6;
            margin: 0;
            font-size: 24px;
        }
        .header p {
            margin: 5px 0;
            color: #666;
        }
        .info-section {
            margin-bottom: 20px;
            padding: 15px;
            background-color: #f8f9fa;
            border-radius: 5px;
        }
        .info-section h2 {
            margin-top: 0;
            color: #3B82F6;
            font-size: 16px;
            border-bottom: 2px solid #3B82F6;
            padding-bottom: 5px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }
        th {
            background-color: #3B82F6;
            color: white;
            padding: 10px;
            text-align: left;
            font-weight: bold;
        }
        td {
            padding: 8px;
            border-bottom: 1px solid #ddd;
        }
        tr:nth-child(even) {
            background-color: #f8f9fa;
        }
        .footer {
            margin-top: 30px;
            padding-top: 20px;
            border-top: 2px solid #ddd;
            text-align: center;
            color: #666;
            font-size: 10px;
        }
        .badge {
            display: inline-block;
            padding: 3px 8px;
            border-radius: 3px;
            font-size: 10px;
            font-weight: bold;
        }
        .badge-active {
            background-color: #10B981;
            color: white;
        }
        .badge-inactive {
            background-color: #EF4444;
            color: white;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Patients Export Report</h1>
        @if(isset($startDate) && isset($endDate) && $startDate && $endDate)
        <p>Date Range: {{ $startDate }} to {{ $endDate }}</p>
        @elseif(isset($startDate) && $startDate)
        <p>From: {{ $startDate }}</p>
        @elseif(isset($endDate) && $endDate)
        <p>Until: {{ $endDate }}</p>
        @endif
        <p>Generated on: {{ $exportDate }}</p>
        <p>Exported by: {{ $exportedBy }}</p>
        <p>Total Patients: {{ $totalPatients }}</p>
    </div>

    <div class="info-section">
        <h2>Patient List</h2>
        <table>
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Phone</th>
                    <th>Gender</th>
                    <th>Birthday</th>
                    <th>Status</th>
                    <th>Appointments</th>
                    <th>Records</th>
                </tr>
            </thead>
            <tbody>
                @forelse($patients as $patient)
                <tr>
                    <td>{{ $patient->id }}</td>
                    <td>{{ $patient->name }}</td>
                    <td>{{ $patient->email }}</td>
                    <td>{{ $patient->phone ?? 'N/A' }}</td>
                    <td>{{ $patient->patient->gender ?? 'N/A' }}</td>
                    <td>{{ $patient->patient->birthday ? \Carbon\Carbon::parse($patient->patient->birthday)->format('M d, Y') : 'N/A' }}</td>
                    <td>
                        <span class="badge {{ $patient->status === 'active' ? 'badge-active' : 'badge-inactive' }}">
                            {{ ucfirst($patient->status) }}
                        </span>
                    </td>
                    <td>{{ $patient->patientAppointments->count() }}</td>
                    <td>{{ $patient->patientRecords->count() }}</td>
                </tr>
                @empty
                <tr>
                    <td colspan="9" style="text-align: center; padding: 20px;">No patients found</td>
                </tr>
                @endforelse
            </tbody>
        </table>
    </div>

    <div class="footer">
        <p>This is a confidential document. Generated by Dental Clinic Management System.</p>
        <p>Page generated at {{ now()->format('Y-m-d H:i:s') }}</p>
    </div>
</body>
</html>


